---
policies:
  - type: commit
    spec:
      header:
        length: 80
        imperative: true
        case: lower
        invalidLastCharacters: .
      body:
        required: false
      dco: true
      gpg:
        required: true
      spellcheck:
        locale: US
      maximumOfOneCommit: false
