site_name: Dasharo Ecosystem Documentation
site_url: https://docs.dasharo.com/
theme:
    name: material
    favicon: images/favicon.png
    logo: images/dasharo-logo.png
extra_css:
    - stylesheets/extra.css
google_analytics:
    - UA-39420295-13
    - auto
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
    - attr_list
    - toc:
        toc_depth: 2
nav:
    - 'Intro': index.md
    - 'Quality Principles':
        - 'Introduction': quality-principles/introduction.md
        - 'Dasharo Quality Criteria': quality-principles/dasharo-quality-criteria.md
    - 'Value proposition':
        - 'Overview': value-prop/overview.md
        - 'Security': value-prop/security.md
        - 'Compatibility': value-prop/compatibility.md
        - 'Performance': value-prop/performance.md
        - 'Marketing': value-prop/marketing.md
        - 'Certification Program':
            - 'Overview': value-prop/certification-program/overview.md
    - 'Development Environment':
        - 'Nix': dev-env/nix-dev-env.md
    - 'Development Process':
        - 'Source code structure': dev-proc/source-code-structure.md
        - 'Versioning': dev-proc/versioning.md
        - 'Features and bug fixes development process': dev-proc/feature-bug-fix-dev-process.md
        - 'Standard Release Process': dev-proc/standard-release-process.md
    - 'Transparent Validation':
        - 'muxPi':
            - 'Theory of Operations': transparent-validation/muxpi/theory-of-operations.md
            - 'Basic validation': transparent-validation/muxpi/basic-validation.md
        - 'Remote Testing Environment':
            - 'Introduction': transparent-validation/rte/introduction.md
            - 'Specification': transparent-validation/rte/v1.1.0/specification.md
            - 'Getting Started': transparent-validation/rte/v1.1.0/getting-started.md
            - 'RTE and PC Engines': transparent-validation/rte/pcengines.md
            - 'RTE Reference OS': transparent-validation/rte/v1.1.0/reference-os.md
            - 'Revision History': transparent-validation/rte/revision-history.md
        - 'SD Wire':
            - 'Getting started': transparent-validation/sd-wire/getting-started.md
            - 'Specification': transparent-validation/sd-wire/specification.md
            - 'Usage': transparent-validation/sd-wire/usage-validation.md
    - 'Supported hardware':
        - 'Hardware Compatibility List': variants/hardware-compatibility-list.md
        - 'Dell OptiPlex':
            - 'Releases': variants/dell_optiplex/releases.md
            - 'Installation manual': variants/dell_optiplex/installation-manual.md
        - 'Asus KGPE-D16':
            - 'Hardware setup': variants/asus_kgpe_d16/setup.md
        - 'Talos II':
            - 'Releases': variants/talos_2/releases.md
            - 'Building manual': variants/talos_2/building-manual.md
            - 'Installation manual': variants/talos_2/installation-manual.md
            - 'Hardware configuration matrix': variants/talos_2/hardware-matrix.md
    - 'Dasharo SKUs':
        - 'Overview': variants/skus-overview.md
        - 'Firewall': variants/firewall.md
        - 'Secure Firewall': variants/secure-firewall.md
        - 'Workstation':
            - 'SKU description': variants/workstation.md
        - 'Server': variants/server.md
        - 'Trustworthy Server': variants/trustworthy-server.md
        - 'Trustworthy Computing': variants/trustworthy-computing.md
        - 'Safety-Critical': variants/safety-critical.md
        - 'Custom': variants/custom.md
    - 'How to work with us?':
        - 'Overview': inquiries/overview.md
        - 'Community Edition': inquiries/community-edition.md
        - 'Sponsorware': inquiries/sponsorware.md
        - 'Commercial inquiries': inquiries/commercial-inquiries.md
    - 'Knowledge base':
        - 'Trolling Topics List':
            - 'Introduction': osf-trolling-list/osf_issues_taxonomy.md
            - 'Firmware build process': osf-trolling-list/build_process.md
            - 'Firmware release process': osf-trolling-list/release_process.md
        - 'Frequently Asked Questions':
            - 'Introduction': osf-trivia-list/introduction.md
    - 'Glossary': glossary.md

