---
site_name: Dasharo Universe
site_url: https://docs.dasharo.com/
theme:
  name: material
  custom_dir: overrides
  favicon: images/favicon.png
  logo: images/dasharo-logo.png
extra_css:
  - stylesheets/extra.css
google_analytics:
  - UA-39420295-13
  - auto
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - meta
  - toc:
      toc_depth: 2
  - pymdownx.tasklist:
      custom_checkbox: true
nav:
  - 'Intro': index.md
  - 'Supported hardware':
      # - 'Hardware Compatibility List': variants/hardware-compatibility-list.md
      - 'Dell OptiPlex':
          - 'Overview': variants/dell_optiplex/overview.md
          - 'Releases': variants/dell_optiplex/releases.md
          - 'Building manual': variants/dell_optiplex/building-manual.md
          #- 'Hardware Configuration Matrix': variants/dell_optiplex/hardware-matrix.md
          - 'Initial deployment': variants/dell_optiplex/initial-deployment.md
          - 'Firmware update': variants/dell_optiplex/firmware-update.md
          - 'Recovery': variants/dell_optiplex/recovery.md
      - 'Asus KGPE-D16':
          - 'Releases': variants/asus_kgpe_d16/releases.md
          - 'Hardware setup': variants/asus_kgpe_d16/setup.md
          - 'Building manual': variants/asus_kgpe_d16/building-manual.md
          - 'Hardware configuration matrix': variants/asus_kgpe_d16/hardware-matrix.md
          - 'Automatic fan control': variants/asus_kgpe_d16/fan-control.md
          - 'Hardware flash protection': variants/asus_kgpe_d16/spi-wp.md
          - 'TPM measured boot': variants/asus_kgpe_d16/tpm-mboot.md
      - 'Talos II':
          - 'Releases': variants/talos_2/releases.md
          - 'Building manual': variants/talos_2/building-manual.md
          - 'Installation manual': variants/talos_2/installation-manual.md
          #- 'Hardware Configuration Matrix': variants/talos_2/hardware-matrix.md
          - 'Test matrix': variants/talos_2/test-matrix.md
          - 'Conference materials': variants/talos_2/conferences.md
      - 'Clevo NV41':
          - 'Releases': variants/clevo_nv41/releases.md
          - 'Building manual': variants/clevo_nv41/building.md
          - 'Updating firmware using fwupd': variants/clevo_nv41/fwupd_usage.md
          - 'EC firmware update': variants/clevo_nv41/ec_update.md
          - 'Flashing with external programmer': variants/clevo_nv41/flashing_external.md
          - 'Flashing with internal programmer': variants/clevo_nv41/flashing_internal.md
          - 'Post-installation steps': variants/clevo_nv41/post_install.md
          - 'Hardware Configuration Matrix': variants/clevo_nv41/hardware-matrix.md
          - 'Logo customization': common-coreboot-docs/custom_logo.md
          - 'Openness score': variants/clevo_nv41/openness_analysis.md
          - 'LVFS report': variants/clevo_nv41/lvfs_report.md
          - 'Dasharo Tools Suite': common-coreboot-docs/dasharo_tools_suite.md
      - 'Tuxedo IBS15':
          - 'Releases': variants/tuxedo_ibs15/releases.md
          - 'Building manual': variants/tuxedo_ibs15/building.md
          - 'Installation manual': variants/tuxedo_ibs15/installation.md
          - 'Post-installation steps': variants/tuxedo_ibs15/post_install.md
          - 'Logo customization': common-coreboot-docs/custom_logo.md
          - 'Hardware Configuration Matrix': variants/tuxedo_ibs15/hardware-matrix.md
      - 'NovaCustom NS5X':
          - 'Releases': variants/novacustom_ns5x/releases.md
          - 'Building manual': variants/novacustom_ns5x/building.md
          - 'Installation manual': variants/novacustom_ns5x/installation.md
          - 'Post-installation steps': variants/novacustom_ns5x/post_install.md
          - 'Logo customization': common-coreboot-docs/custom_logo.md
          - 'RGB keyboard': variants/novacustom_ns5x/rgb_keyboard.md
          - 'Test matrix': variants/novacustom_ns5x/test-matrix.md
      - 'Protectli VP4620':
          - 'Releases': variants/protectli_vp4620/releases.md
          - 'Building manual': variants/protectli_vp4620/building-manual.md
          - 'Installation manual': variants/protectli_vp4620/installation-manual.md
          - 'Hardware Configuration Matrix': variants/protectli_vp4620/hardware-matrix.md
      - 'MSI PRO Z690-A WIFI DDR4':
          - 'Overview': variants/msi_z690/overview.md
          - 'Releases': variants/msi_z690/releases.md
          - 'Building manual': variants/msi_z690/building-manual.md
          - 'Installation manual': variants/msi_z690/installation-manual.md
          - 'Recovery': variants/msi_z690/recovery.md
          - 'Hardware Configuration Matrix': variants/msi_z690/hardware-matrix.md
          - 'Test matrix': variants/msi_z690/test-matrix.md
          - 'Development': variants/msi_z690/development.md
# - 'Development Environment':
#     - 'Nix': dev-env/nix-dev-env.md
  - 'Development Process':
      - 'Source code structure': dev-proc/source-code-structure.md
      - 'Dasharo Product Guidelines: SMBIOS Information': dev-proc/smbios-rules.md
      - 'Versioning': dev-proc/versioning.md
      - 'Features and bug fixes development process': dev-proc/feature-bug-fix-dev-process.md
      - 'Standard Release Process': dev-proc/standard-release-process.md
# - 'Dasharo SKUs':
    # - 'Overview': variants/skus-overview.md
    # - 'Firewall': variants/firewall.md
    # - 'Secure Firewall': variants/secure-firewall.md
    # - 'Workstation':
    #     - 'SKU description': variants/workstation.md
    # - 'Server': variants/server.md
    # - 'Trustworthy Server': variants/trustworthy-server.md
    # - 'Trustworthy Computing': variants/trustworthy-computing.md
    # - 'Safety-Critical': variants/safety-critical.md
    # - 'Custom': variants/custom.md
# - 'How to work with us?':
#     - 'Overview': inquiries/overview.md
#     - 'Community Edition': inquiries/community-edition.md
#     - 'Sponsorware': inquiries/sponsorware.md
#     - 'Commercial inquiries': inquiries/commercial-inquiries.md
  - 'Knowledge base':
      - 'Common coreboot documentation':
          - 'Vboot signing': common-coreboot-docs/vboot_signing.md
    # - 'Trolling Topics List':
    #     - 'Introduction': osf-trolling-list/osf_issues_taxonomy.md
  - 'Frequently Asked Questions':
      - 'Introduction': osf-trivia-list/introduction.md
      - 'Deployment': osf-trivia-list/deployment.md
      - 'Firmware build process': osf-trolling-list/build_process.md
    # - 'Firmware release process': osf-trolling-list/release_process.md
      - 'Trusted Computing': osf-trolling-list/trusted_computing.md
      - 'Jira Service Management': osf-trolling-list/jsm_documentation.md
  - 'Ecosystem':
      - 'Overview': ecosystem/overview.md
    # - 'Customer Infrastructure': ecosystem/customer-infrastructure.md
      - 'Transparent Validation':
        # - 'Overview': ecosystem/transparent-validation.md
        # - 'Testing Infrastructure': ecosystem/testing-infrastructure.md
        # - 'Hardware Laboratory': ecosystem/hardware-infrastructure.md
          - 'muxPi':
              - 'Theory of Operations': transparent-validation/muxpi/theory-of-operations.md
              - 'Basic validation': transparent-validation/muxpi/basic-validation.md
          - 'Remote Testing Environment':
              - 'Introduction': transparent-validation/rte/introduction.md
              - 'Specification': transparent-validation/rte/v1.1.0/specification.md
              - 'Getting Started': transparent-validation/rte/v1.1.0/getting-started.md
              - 'RTE and PC Engines': transparent-validation/rte/pcengines.md
              - 'RTE Reference OS': transparent-validation/rte/v1.1.0/reference-os.md
              - 'Revision History': transparent-validation/rte/revision-history.md
          - 'SD Wire':
              - 'Getting started': transparent-validation/sd-wire/getting-started.md
              - 'Specification': transparent-validation/sd-wire/specification.md
              - 'Usage': transparent-validation/sd-wire/usage-validation.md
    # - 'Secure Storage': ecosystem/secure-storage.md
    # - 'Signing Server': ecosystem/signing-server.md
    # - 'Attestation Server': ecosystem/attestation-server.md
    # - 'Deployment and Provisioning Server': ecosystem/deployment-and-provisioning-server.md
    # - 'Reference OS': ecosystem/reference-os.md
    # - 'Publishing Server': ecosystem/publishing-server.md
    # - 'End User Device': ecosystem/end-user.md
      - 'Dasharo Test Specification':
          - 'Overview': unified-test-documentation/overview.md
          - 'Generic Test Setup': unified-test-documentation/generic-test-setup.md
          - 'Test Matrix': unified-test-documentation/test-matrix.md
          - 'Dasharo compatibility':
              - 'Coreboot Base Port': unified-test-documentation/dasharo-compatibility/100-coreboot-base-port.md
              - 'Memory HCL': unified-test-documentation/dasharo-compatibility/301-memory-hcl.md
              - 'Custom Boot Menu Key': unified-test-documentation/dasharo-compatibility/303-custom-boot-menu-key.md
              - 'Custom Logo': unified-test-documentation/dasharo-compatibility/304-custom-logo.md
              - 'Petitboot payload support': unified-test-documentation/dasharo-compatibility/31V-petitboot-payload-support.md
              - 'Heads bootloader support': unified-test-documentation/dasharo-compatibility/31U-heads-bootloader-support.md
              - 'SMBIOS': unified-test-documentation/dasharo-compatibility/31L-smbios.md
              - 'Device Tree': unified-test-documentation/dasharo-compatibility/31W-device-tree.md
              - 'USB HID and MSC support': unified-test-documentation/dasharo-compatibility/306-usb-hid-and-msc-support.md
              - 'CPU status': unified-test-documentation/dasharo-compatibility/31T-cpu-status.md
              - 'NVME support': unified-test-documentation/dasharo-compatibility/312-nvme-support.md
              - 'Network boot': unified-test-documentation/dasharo-compatibility/315-network-boot.md
              - 'SD card reader': unified-test-documentation/dasharo-compatibility/316-sdcard-reader.md
              - 'USB camera': unified-test-documentation/dasharo-compatibility/317-usb-camera.md
              - 'Wi-Fi and Bluetooth support': unified-test-documentation/dasharo-compatibility/318-m2-wifi-bluetooth.md
              - 'Display ports and LCD': unified-test-documentation/dasharo-compatibility/31E-display-ports-and-lcd.md
              - 'Audio Subsystem': unified-test-documentation/dasharo-compatibility/31F-audio-subsystem.md
              - 'USB type C support': unified-test-documentation/dasharo-compatibility/31H-usb-type-c.md
              - 'Memtest payload support': unified-test-documentation/dasharo-compatibility/30L-memtest-payload-support.md
              - 'Windows 11 booting': unified-test-documentation/dasharo-compatibility/31A-windows-booting.md
              - 'Sleep mode': unified-test-documentation/dasharo-compatibility/31J-sleep-mode.md
              - 'UEFI compatible interface': unified-test-documentation/dasharo-compatibility/30M-uefi-compatible-interface.md
              - 'UEFI Shell': unified-test-documentation/dasharo-compatibility/30P-uefi-shell.md
              - 'Platform suspend and resume': unified-test-documentation/dasharo-compatibility/31M-platform-suspend-and-resume.md
              - 'FreeBSD support': unified-test-documentation/dasharo-compatibility/307-freebsd-support.md
              - 'Debian Stable and Ubuntu LTS support': unified-test-documentation/dasharo-compatibility/308-debian-stable-and-ubuntu-lts-support.md
              - 'USB detection': unified-test-documentation/dasharo-compatibility/31O-usb-detect.md
              - 'USB booting': unified-test-documentation/dasharo-compatibility/31N-usb-boot.md
              - 'coreboot Fan control': unified-test-documentation/dasharo-compatibility/S31-coreboot-fan-control.md
              - 'Custom Fan Curve': unified-test-documentation/dasharo-compatibility/S30-fan-control.md
              - 'Embedded Controller and Super I/O initialization ': unified-test-documentation/dasharo-compatibility/31G-ec-and-superio.md
              - 'Nvidia Graphics support': unified-test-documentation/dasharo-compatibility/319-nvidia-graphics.md
              - 'Flash write protection': unified-test-documentation/dasharo-compatibility/31P-flash-write-protection.md
              - 'Custom Network Boot entries': unified-test-documentation/dasharo-compatibility/30A-custom-network-boot-entries.md
              - 'M.2 automatic SATA/NVMe switching support': unified-test-documentation/dasharo-compatibility/31I-nvme-switching.md
              - 'miniPCIe slot verification': unified-test-documentation/dasharo-compatibility/31K-minipcie-verification.md
              - 'eMMC support': unified-test-documentation/dasharo-compatibility/31M-emmc-support.md
          - 'Dasharo security':
              - 'TPM support': unified-test-documentation/dasharo-security/200-tpm-support.md
              - 'Verified Boot': unified-test-documentation/dasharo-security/201-verified-boot.md
              - 'Measured Boot': unified-test-documentation/dasharo-security/203-measured-boot.md
              - 'Secure Boot': unified-test-documentation/dasharo-security/206-secure-boot.md
          - 'Dasharo performance':
              - 'Coreboot boot measure': unified-test-documentation/dasharo-performance/400-coreboot-boot-measure.md
      - 'Roadmap': ecosystem/roadmap.md
  - 'Quality Principles': quality-principles/introduction.md
    # - 'Introduction':
    # - 'Dasharo Quality Criteria': quality-principles/dasharo-quality-criteria.md
  - 'Value proposition':
      - 'Overview': value-prop/overview.md
      - 'Security': value-prop/security.md
      - 'Compatibility': value-prop/compatibility.md
    # - 'Performance': value-prop/performance.md
      - 'Marketing': value-prop/marketing.md
    # - 'Certification Program':
    #     - 'Overview': value-prop/certification-program/overview.md
  - 'Projects':
      - 'TrenchBoot Anti Evil Maid': projects/trenchboot-aem.md
  - 'Glossary': glossary.md
