site_name: Dasharo Ecosystem Documentation
theme:
    name: material
    favicon: images/favicon.png
    logo: images/dasharo-logo.png
extra_css:
    - stylesheets/extra.css
google_analytics:
    - UA-39420295-13
    - auto
nav:
    - 'Intro': index.md
    - 'Dasharo Trolling topics list':
        - 'Introduction': osf-trolling-list/osf_issues_taxonomy.md
        - 'Firmware build process': osf-trolling-list/build_process.md
    - 'Development Environment':
        - 'Nix': dev-env/nix-dev-env.md
    - 'Stock Keeping Units (SKUs)':
        - 'Overview': variants/skus-overview.md
        - 'Secure Firewall': variants/secure-firewall.md
        - 'Workstation': variants/workstation.md
        - 'Trustworthy Server': variants/trustworthy-server.md

