site_name: Dasharo Ecosystem Documentation
theme:
    name: material
    favicon: images/favicon.png
    logo: images/dasharo-logo.png
extra_css:
    - stylesheets/extra.css
google_analytics:
    - UA-39420295-13
    - auto
nav:
    - 'Intro': index.md
    - 'Trolling Topics List':
        - 'Introduction': osf-trolling-list/osf_issues_taxonomy.md
        - 'Firmware build process': osf-trolling-list/build_process.md
    - 'Value proposition':
        - 'Overview': value-prop/overview.md
        - 'Security': value-prop/security.md
        - 'Compatibility': value-prop/compatibility.md
        - 'Performance': value-prop/performance.md
        - 'Marketing': value-prop/marketing.md
    - 'Development Environment':
        - 'Nix': dev-env/nix-dev-env.md
    - 'Transparent Validation':
        - 'Remote Testing Environment': transparent-validation/rte/introduction.md
        - 'RTE v1.1.0 User Manual': transparent-validation/rte/v1.1.0/specifciation.md
    - 'Stock Keeping Units (SKUs)':
        - 'Overview': variants/skus-overview.md
        - 'Firewall': variants/firewall.md
        - 'Secure Firewall': variants/secure-firewall.md
        - 'Workstation': variants/workstation.md
        - 'Server': variants/server.md
        - 'Trustworthy Server': variants/trustworthy-server.md
        - 'Trustworthy Computing': variants/trustworthy-computing.md
        - 'Safety-Critical': variants/safety-critical.md
        - 'Custom': variants/custom.md
    - 'How to work with us?':
        - 'Overview': inquiries/overview.md
        - 'Community Edition': inquiries/community-edition.md
        - 'Sponsorware': inquiries/sponsorware.md
        - 'Commercial inquiries': inquiries/commercial-inquiries.md

