site_name: Dasharo Ecosystem Documentation
site_url: https://docs.dasharo.com/
theme:
    name: material
    favicon: images/favicon.png
    logo: images/dasharo-logo.png
extra_css:
    - stylesheets/extra.css
google_analytics:
    - UA-39420295-13
    - auto
markdown_extensions:
    - pymdownx.highlight
    - pymdownx.superfences
    - pymdownx.keys
nav:
    - 'Intro': index.md
    - 'Trolling Topics List (OSFTTL)':
        - 'Introduction': osf-trolling-list/osf_issues_taxonomy.md
        - 'Firmware build process': osf-trolling-list/build_process.md
    - 'Trivia Questions List (OSFTQL)':
        - 'Trivial questions': osf-trivia-list/introduction.md
    - 'Quality Principles':
        - 'Introduction': quality-principles/introduction.md
    - 'Value proposition':
        - 'Overview': value-prop/overview.md
        - 'Security': value-prop/security.md
        - 'Compatibility': value-prop/compatibility.md
        - 'Performance': value-prop/performance.md
        - 'Marketing': value-prop/marketing.md
        - 'Certification Program':
            - 'Overview': value-prop/certification-program/overview.md
    - 'Development Environment':
        - 'Nix': dev-env/nix-dev-env.md
    - 'Transparent Validation':
        - 'muxPi':
            - 'Theory of Operations': transparent-validation/muxpi/theory-of-operations.md
            - 'Basic validation': transparent-validation/muxpi/basic-validation.md
        - 'Remote Testing Environment':
            - 'Introduction': transparent-validation/rte/introduction.md
            - 'Specification': transparent-validation/rte/v1.1.0/specification.md
            - 'Getting Started': transparent-validation/rte/v1.1.0/getting-started.md
            - 'RTE and PC Engines': transparent-validation/rte/pcengines.md
            - 'RTE Reference OS': transparent-validation/rte/v1.1.0/reference-os.md
            - 'Revision History': transparent-validation/rte/revision-history.md
        - 'SD Wire':
            - 'Getting started': transparent-validation/sd-wire/getting-started.md
            - 'Specification': transparent-validation/sd-wire/specification.md
            - 'Usage': transparent-validation/sd-wire/usage-validation.md
    - 'Stock Keeping Units (SKUs)':
        - 'Overview': variants/skus-overview.md
        - 'Firewall': variants/firewall.md
        - 'Secure Firewall': variants/secure-firewall.md
        - 'Workstation':
            - 'SKU description': variants/workstation.md
            - 'Releases': variants/workstation/releases.md
            - 'Installation manual': variants/workstation/installation-manual.md
        - 'Server': variants/server.md
        - 'Trustworthy Server': variants/trustworthy-server.md
        - 'Trustworthy Computing': variants/trustworthy-computing.md
        - 'Safety-Critical': variants/safety-critical.md
        - 'Custom': variants/custom.md
    - 'How to work with us?':
        - 'Overview': inquiries/overview.md
        - 'Community Edition': inquiries/community-edition.md
        - 'Sponsorware': inquiries/sponsorware.md
        - 'Commercial inquiries': inquiries/commercial-inquiries.md
    - 'Glossary': glossary.md

