#!/usr/bin/env python3
import json
from pathlib import Path

MAPPING = Path('/tmp/wuxie/dts-configs/configs/docs_supported_platforms.json')
OUT = Path('docs/dasharo-tools-suite/documentation/_generated-supported-hardware-matrix.md')


def to_display(vendor, model, board):
    v = vendor.replace('_', ' ')
    if board:
        return f"{v} / {model} / {board}"
    return f"{v} / {model}"


def main():
    data = json.loads(MAPPING.read_text())
    entries = data.get('entries', [])
    lines = [
        '<!-- Generated by scripts/generate_dts_supported_hardware_matrix.py -->',
        '',
        '| Vendor/Model | Dasharo release id |',
        '|---|---|',
    ]
    for e in entries:
        disp = to_display(e['system_vendor'], e['system_model'], e.get('board_model'))
        rel = e.get('dasharo_rel_name', '')
        lines.append(f"| `{disp}` | `{rel}` |")

    OUT.write_text('\n'.join(lines) + '\n')
    print(f'Wrote {OUT} with {len(entries)} rows')


if __name__ == '__main__':
    main()
